<Project>
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <IsAotCompatible Condition="'$(IsTestProject)' != 'true'">true</IsAotCompatible>
    <Authors>Teknesyum</Authors>
    <Product>DustyBytes</Product>
    <Version>0.5.0</Version>
  </PropertyGroup>
</Project>
